// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO0p-6XbF5OwKKvQGKiHu7fweValxS4uA',
    appId: '1:764102569793:web:dab640cc4c8cf3e8c0fbc0',
    messagingSenderId: '764102569793',
    projectId: 'yene-a3e5f',
    authDomain: 'yene-a3e5f.firebaseapp.com',
    storageBucket: 'yene-a3e5f.appspot.com',
    measurementId: 'G-2TV5D6RBFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3wArB9wHIbvt6fxF3BTXdAjvwYoCdsE',
    appId: '1:764102569793:android:d8d4207b257415e4c0fbc0',
    messagingSenderId: '764102569793',
    projectId: 'yene-a3e5f',
    storageBucket: 'yene-a3e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCmSRBQjSvAJqwpR9moQ86aKQpffZvzLM',
    appId: '1:764102569793:ios:f85bec973281de0dc0fbc0',
    messagingSenderId: '764102569793',
    projectId: 'yene-a3e5f',
    storageBucket: 'yene-a3e5f.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCmSRBQjSvAJqwpR9moQ86aKQpffZvzLM',
    appId: '1:764102569793:ios:636a5bf39df2d13ec0fbc0',
    messagingSenderId: '764102569793',
    projectId: 'yene-a3e5f',
    storageBucket: 'yene-a3e5f.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
